### ISSUE TITLE
ACF fieldsets are exposed for all post types, even if the 'location' rules don't allow you to edit them

### ISSUE THREAD

**Issue by edtjones** [rooftopcms/rooftop-acf-exposer#1]
If you set up a set of rules to limit an ACF fieldset to only a certain post type, it doesn't make much sense to expose them in other post types. See screenie - I would expect this fieldset only to be available in responses for the appropriate post type (product_plan in this case)

![screen shot 2015-10-29 at 23 20 24](https://cloud.githubusercontent.com/assets/4377783/10834730/c4222d0c-7e93-11e5-8871-dd612b7bed8a.png)

**Comment by foxpaul** [comment]
Hey @edtjones - what other content types is your fieldset being returned with? I've tried adding some fields to a custom type but I don't see them returned with other content types.

**Comment by edtjones** [comment]
Steps to recreate @foxpaul:

* Create 2 custom post types
* Create 2 acf field sets, with one field each (for expedience)
* Assign one acf fieldset to the first post type, and the other to the second
* Create one post of each type
* The JSON returned for either will include both fieldsets, even though each should (I think) only have the one associated with it
